baseURL = 'https://emacs-eask.github.io/'
languageCode = 'en-us'
title = 'Emacs Eask'
license = 'MIT'

theme = [
  'geekdoc',
]

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocToC = 3
  geekdocLogo = './logo.png'
  geekdocRepo = 'https://github.com/emacs-eask/eask/'
  
