baseURL = 'https://emacs-eask.github.io/'
languageCode = 'en-us'
title = 'Emacs Eask'
license = 'MIT'

theme = [
  'geekdoc',
]

pygmentsUseClasses = true
pygmentsCodeFences = true

disablePathToLower = true
enableGitInfo = true

[markup.highlight]
  noClasses = false

[params]
  geekdocToC = 3
  geekdocLogo = './assets/images/eask-small.png'
  geekdocRepo = 'https://github.com/emacs-eask/eask/'
  
