name: Build

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - lisp/**
      - cmds/**
      - src/**
      - test/**
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: 0.6.16
  NODE: node16

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
        - linux-x64
        - macos-x64
        - win-x64
        - linux-arm64
        - macos-arm64
        - win-arm64

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install pkg
      run: npm install -g pkg

    - uses: actions/checkout@v2

    - name: Preparing...
      run: npm install

    - name: Building...
      run: pkg package.json -t ${{ env.NODE }}-${{ matrix.targets }}

    - name: Prepare content...
      run: |
        mv lisp dist
        mv COPYING dist
        mv README.md dist

    - name: Uploading...
      uses: actions/upload-artifact@v1
      with:
        name: eask_${{ env.VERSION }}_${{ matrix.targets }}
        path: dist
