name: Commands

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - snapshot

    steps:
    - uses: purcell/setup-emacs@master
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: jcs090218/setup-emacs-windows@master
      if: matrix.os == 'windows-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v2

    - name: Prepare Eask (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        npm install
        chmod -R 777 ./
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Prepare Eask (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm install
        echo "${{ github.workspace }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Test commands (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        #${{ github.workspace }}/test/commands/test_global.sh
        #${{ github.workspace }}/test/commands/test_local.sh
        ${{ github.workspace }}/test/commands/exec/make.sh

    - name: Test commands (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        #${{ github.workspace }}/test/commands/test_global.ps1
        #${{ github.workspace }}/test/commands/test_local.ps1
        ${{ github.workspace }}/test/commands/exec/make.ps1
