name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 25.3
          - 26.3
          - 27.2
          - snapshot

    steps:
    - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - if: matrix.os == 'windows-latest'
      uses: jcs090218/setup-emacs-windows@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v2
    - name: Test commands
      run: sh ./bin/commands.sh
